version: '3'
services:
  macudev:
    build: .
    restart: always
    container_name: macudev
    environment:
      - VIRTUAL_HOST=macu.ptah.tech
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=macu.ptah.tech
      - LETSENCRYPT_EMAIL=mariaclaudiaperezes@gmail.com
    links:
      - mysql57

  mysql57:
    build: containers/mysql
    environment:
      - MYSQL_ROOTPASSWORD=toor
    volumes:
      - /home/arwo/dockers/volumes/macu/mysql:/var/lib/mysql
      
networks:
  default:
     external:
       name: webproxy
